service: aws-iot-example-ff

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "dynamodb:Scan"
       - "dynamodb:Query"
      Resource:
        Fn::GetAtt:
          - "StateTable"
          - "Arn"
  environment:
   REGION: ${{opt:stage, self:provider.region}}
   TABLE: ${{self:custom.stateTable}}

custom:
  # Rule for reading the state messages and include the clientId in the package as deviceId
  stateRuleSQL: "SELECT *, topic(3) as deviceId, FROM 'sensors/temperature/+/state'"
  # DynamoDB Table name
  stateTable: StateTable


functions:
  getData:
    handler: handler.getData
    events:
      - http:
          path: data
          method: get
          cors: true
      # - iot:
      #     sql: "SELECT * FROM 'some_topic'"

resources:
  Resources:
    # Table for holding state data
    StateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${{self:custom.stateTable}}
        SSESpecification:
          SSEEnabled: true
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    # IAM Role & Policy to allow AWS IoT Service to write in our DynamoDB Table
    StateRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: state-iot-write-dynamo-ff
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - iot.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: "statedynamodbwrite"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "dynamodb:PutItem"
                    - "dynamodb:BatchWriteItem"
                  Resource:
                    Fn::GetAtt:
                      - "StateTable"
                      - "Arn"
    # Rule to forward state messages into the DynamoDB
    StateRule:
      Type: "AWS::IoT::TopicRule"
      Properties:
        RuleName: state_to_dynamo_ff
        TopicRulePayload:
          RuleDisabled: false
          Sql: ${{self:custom.stateRuleSQL}}
          AwsIotSqlVersion: "2016-03-23"
          Actions:
            -
              DynamoDBv2:
                RoleArn:
                  Fn::GetAtt:
                    - "StateRole"
                    - "Arn"
                PutItem:
                  TableName: StateTable
